feat: added automatic detection of third-party images from Helm charts. (#598)
* feat: added auto-discovery 3dr party images from charts

* chore: added needs

* chore: added one line json output

* chore: bump and pin Azure/setup-helm version

* chore: changed helm version to latest stable

* fix: yq failure when there are no dependencies in Chart.yaml

* fix: yq failure when there are no dependencies in Chart.yaml

* chore: pretty yaml

* fix: safe yaml load and changed expression to filter images

* chore: added debug messages

* chore: added debug messages

* chore: added debug messages

* chore: added debug messages

* chore: added debug messages

* chore: added debug messages

* chore: added debug messages

* fix: fixed condition

* chore: added debug messages

* chore: added debug messages

* chore: added debug messages

* chore: added debug messages

* chore: added debug messages

* chore: added debug messages

* fix: fixed path to config file

* chore: minor improvements

* chore: minor improvements

* chore: minor improvements

* fix: config file path

* feat: added `set` array to charts in configuration

* feat: added `set` array to charts in configuration

* feat: added `set` array to charts in configuration

* chore: added --debug

* fix: removed some config parameters

* chore: added qubership-env-checker

* chore: added qubership-env-checker

* chore: fixes for linters

* feat: added summary

* chore: fix typo

* fix: matrix generation

* fix: matrix generation

* chore: fixes for linters

diff --git a/.github/workflows/3rd-party-sec-scan.yaml b/.github/workflows/3rd-party-sec-scan.yaml
--- a/.github/workflows/3rd-party-sec-scan.yaml
+++ b/.github/workflows/3rd-party-sec-scan.yaml
@@ -41,17 +41,232 @@ permissions:
 
 env:
   CONFIG_FILE: .qubership/3rd-party-sec-scan-config.yaml
-  REPORT_BRANCH: reports
+  IMAGES_CONFIG_FILE: final-output/final-3rd-party-images.yaml
+  ORG_PREFIX: 'ghcr.io/netcracker'
 jobs:
+  init:
+    runs-on: ubuntu-24.04
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
+    steps:
+      - name: Checkout current repository
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          persist-credentials: true
+
+      - name: Generate matrix from config
+        id: set-matrix
+        run: |
+          if [[ ! -f "${CONFIG_FILE}" ]]; then
+            echo "::error::Config file not found"
+            exit 1
+          fi
+
+          REPOS=$(yq e '.repositories[].name' "${CONFIG_FILE}" -r | jq -R . | jq -s -c .)
+          MATRIX_JSON="{\"repo\": $REPOS}"
+          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT
+          echo "Generated matrix: $MATRIX_JSON"
+
+  process-repos:
+    needs: init
+    runs-on: ubuntu-24.04
+    name: "${{ matrix.repo }}"
+    strategy:
+      fail-fast: false
+      matrix: ${{ fromJson(needs.init.outputs.matrix) }}
+
+    steps:
+      - name: Install Helm
+        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
+
+      - name: Checkout current repository (for config)
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          persist-credentials: true
+
+      - name: Process repository ${{ matrix.repo }}
+        env:
+          REPO_NAME: ${{ matrix.repo }}
+          OWNER: Netcracker
+        run: |
+          # Extracting charts for the repo from config
+          CHARTS=$(yq e ".repositories[] | select(.name == \"$REPO_NAME\") | .charts[].path" ${CONFIG_FILE} -r | grep -v '^null$')
+
+          if [[ -z "$CHARTS" ]]; then
+            echo "::warning::No charts found for $REPO_NAME"
+            exit 0
+          fi
+
+          # Cloning repository
+          TMP_DIR="temp-$REPO_NAME"
+          rm -rf "$TMP_DIR"
+          git clone --depth=1 "https://github.com/$OWNER/$REPO_NAME.git" "$TMP_DIR" || {
+            echo "::warning::Cannot clone $OWNER/$REPO_NAME"
+            exit 0
+          }
+
+          mkdir -p output
+          # Array to hold all 3rd-party images for the repo
+          # THIRD_PARTY_ALL=()
+          echo "$CHARTS" | while read -r chart_rel_path; do
+            CHART_PATH="$TMP_DIR/$chart_rel_path"
+
+            if [[ ! -f "$CHART_PATH" ]]; then
+              echo "::warning::$chart_rel_path not found in $REPO_NAME"
+              continue
+            fi
+
+            CHART_DIR=$(dirname "$CHART_PATH")
+
+            echo "→ Processing chart: $chart_rel_path"
+
+            # Searching for condition
+            CONDITIONS=$(yq e '.dependencies[] // [] | select(has("condition")) | .condition' "$CHART_PATH" -r | grep -v '^null$' || true)
+            echo "  Found conditions: $CONDITIONS"
+
+            DEBUG_VALUES="$TMP_DIR/debug-values.yaml"
+            : > "$DEBUG_VALUES"
+
+            if [[ -n "$CONDITIONS" ]]; then
+              while IFS= read -r cond; do
+                IFS='.' read -ra parts <<< "$cond"
+                yaml_line=""
+                for i in "${!parts[@]}"; do
+                  if (( i < ${#parts[@]}-1 )); then
+                    spaces=$(printf '%*s' "$i" '')
+                    yaml_line+="${parts[i]}:\n ${spaces}"
+                  else
+                    yaml_line+="${parts[i]}: true"
+                  fi
+                done
+                echo -e "$yaml_line" >> "$DEBUG_VALUES"
+                echo "" >> "$DEBUG_VALUES"
+              done <<< "$CONDITIONS"
+            else
+              echo "# No conditional dependencies" > "$DEBUG_VALUES"
+            fi
+            echo "[DEBUG]: Generated debug values for conditions: $(cat "$DEBUG_VALUES")"
+
+            # Helm dependency build
+            (cd "$CHART_DIR" && helm dependency build) || echo "::warning::helm dependency build failed for $chart_rel_path"
+
+            # Building --set arguments for chart
+            SET_VARS=$(yq e ".repositories[] | select(.name == \"$REPO_NAME\") | .charts[] | select(.path == \"$chart_rel_path\") | .set // [] | join(\" --set \")" ${CONFIG_FILE} -r)
+            if [[ -z "${SET_VARS}" ]]; then
+              echo "Set vars: none"
+            else
+              SET_VARS="--set ${SET_VARS}"
+              echo "Set vars: $SET_VARS"
+            fi
+
+            # Running helm template
+            echo "  → Running helm template"
+            helm template "release-$REPO_NAME" "$CHART_DIR" \
+              -f "$DEBUG_VALUES" \
+              --debug $SET_VARS \
+              | yq ' .. | .image? | select(.) ' -   | sort -u
+            helm template "release-$REPO_NAME" "$CHART_DIR" \
+              $SET_VARS --debug \
+              -f "$DEBUG_VALUES" > "$TMP_DIR/rendered.yaml" 2> "$TMP_DIR/helm-debug.log" || {
+                echo "::warning::helm template failed for $chart_rel_path"
+                cat "$TMP_DIR/helm-debug.log" | tail -n 30
+                continue
+              }
+
+            # Extracting images from rendered manifests
+            IMAGES=$(cat "$TMP_DIR/rendered.yaml" | yq '.. | .image? | select(.)' - | grep -v -- '---' | sort -u)
+            echo "  Found images:"
+            echo "$IMAGES"
+            if [[ -z "${IMAGES}" ]]; then
+              echo "  No images found in $chart_rel_path"
+              continue
+            fi
+
+            # Filter internal images.
+            :> "$TMP_DIR/3rd-party-images.txt"
+            while IFS= read -r img; do
+              echo "Image: $img"
+              echo "ORG_PREFIX: $ORG_PREFIX"
+              if [[ "$img" == "${ORG_PREFIX}"* ]]; then
+                continue
+              else
+                echo "   Adding 3rd-party image: $img"
+                #THIRD_PARTY_ALL+=("$img")
+                echo "$img" >> "$TMP_DIR/3rd-party-images.txt"
+                #echo "[DEBUG]: ${#THIRD_PARTY_ALL[*]}"
+              fi
+            done <<< "$IMAGES"
+
+          done  # End of the loop over charts
+          mapfile -t THIRD_PARTY_ALL < "$TMP_DIR/3rd-party-images.txt"
+          echo "Number of All 3rd-party images for $REPO_NAME: ${#THIRD_PARTY_ALL[*]}"
+
+          rm -rf "$TMP_DIR"
+
+          # Saving unique images for the repo
+          if [[ ${#THIRD_PARTY_ALL[*]} -gt 0 ]]; then
+            UNIQUE_IMAGES=$(printf "%s\n" "${THIRD_PARTY_ALL[@]}" | sort -u)
+            OUTPUT_FILE="output/$REPO_NAME-3rd-party-images.yaml"
+            echo "$REPO_NAME:" > "$OUTPUT_FILE"
+            while IFS= read -r img; do
+              echo "  - $img" >> "$OUTPUT_FILE"
+            done <<< "$UNIQUE_IMAGES"
+            cat "$OUTPUT_FILE"
+          else
+            echo "No 3rd-party images for $REPO_NAME"
+          fi
+
+      - name: Upload artifact for ${{ matrix.repo }}
+        if: always()
+        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6.0.0
+        with:
+          name: images-${{ matrix.repo }}
+          path: output/*.yaml
+          if-no-files-found: ignore
+
+  combine-results:
+    needs: process-repos
+    runs-on: ubuntu-24.04
+    if: always()
+    steps:
+      - name: Download all artifacts
+        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
+        with:
+          path: artifacts
+          pattern: images-*
+          merge-multiple: true
+
+      - name: Combine into final file
+        run: |
+          mkdir -p final-output
+          ls -la artifacts
+
+          for f in artifacts/*.yaml; do
+              cat "$f" >> ${IMAGES_CONFIG_FILE}
+          done
+
+          echo ""
+          echo "Final combined file:"
+          cat ${IMAGES_CONFIG_FILE} || echo "(empty)"
+
+      - name: Upload final artifact
+        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6.0.0
+        with:
+          name: 3rd-party-images
+          path: ${{ env.IMAGES_CONFIG_FILE }}
+          if-no-files-found: warn
+
   load-config:
+    needs: combine-results
     runs-on: ubuntu-latest
     outputs:
       packages: ${{ steps.config.outputs.packages }}
     steps:
-      - name: Checkout
-        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+      - name: Download config artifact
+        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
         with:
-          persist-credentials: false
+          name: 3rd-party-images
+          path: final-output
       - name: Read config
         id: config
         run: |
@@ -61,12 +276,12 @@ jobs:
           echo "continue-on-error: ${{ inputs.continue-on-error }}"
           echo "only-fixed: ${{ inputs.only-fixed }}"
           echo "1. ==================================================================================="
-          yq -oj '.' $CONFIG_FILE
+          yq -oj '.' ${IMAGES_CONFIG_FILE}
           echo "2. ==================================================================================="
-          yq -oj '.' $CONFIG_FILE | jq -c 'to_entries | map({repo: .key, image: .value[]}) | {packages: .}'
+          yq -oj '.' ${IMAGES_CONFIG_FILE} | jq -c 'to_entries | map({repo: .key, image: .value[]}) | {packages: .}'
           echo "3. ==================================================================================="
 
-          packages=$(yq -oj '.' $CONFIG_FILE | jq -c 'to_entries | map({repo: .key, image: .value[]})')
+          packages=$(yq -oj '.' ${IMAGES_CONFIG_FILE} | jq -c 'to_entries | map({repo: .key, image: .value[]})')
           echo "packages=$packages" >> $GITHUB_OUTPUT
 
   security-scan-matrix:
@@ -99,10 +314,33 @@ jobs:
 
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout
-        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+      - name: Download config artifact
+        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
         with:
-          persist-credentials: false
+          name: 3rd-party-images
+          path: final-output
+
+      - name: Create summary
+        run: |
+          # shellcheck disable=SC2016
+          yq -r '
+            to_entries[] as $entry |
+
+            "### \($entry.key)\n\n" +
+
+            "| image | tag |\n|---|----|\n" +
+
+            ($entry.value |
+              map(
+                split(":") as $p |
+                "| \($p[0]) | \($p[1] // \"latest\") |"
+              ) |
+              join("\n")
+            ) +
+
+            "\n---\n"
+          ' "${IMAGES_CONFIG_FILE}" > all-components.md
+          cat all-components.md >> $GITHUB_STEP_SUMMARY
 
       - name: Download artifacts
         uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
@@ -131,10 +369,9 @@ jobs:
           mkdir -p $report_dir
           report_file_path=${report_dir}/${report_file_name}
           echo "Report file path: ${report_file_path}"
-          for component in $(yq 'keys | .[]' ${CONFIG_FILE} | paste -sd ' ' -); do
+          for component in $(yq 'keys | .[]' ${IMAGES_CONFIG_FILE} | paste -sd ' ' -); do
             echo "[INFO]: Processing $component's images..."
-            images=$(yq -r '.["'${component}'"] | join(" ")' ${CONFIG_FILE})
-            #images=$(yq e ".${component}[]" ${CONFIG_FILE})
+            images=$(yq -r '.["'${component}'"] | join(" ")' ${IMAGES_CONFIG_FILE})
             for image in $images; do
               echo "Image: $image"
               SHORT_NAME=${image##*/}
@@ -166,4 +403,3 @@ jobs:
           echo "REPORT_FILE_PATH=${report_file_path}" >> $GITHUB_ENV
           echo "Uploading report to s3://$S3_BUCKET/${report_file_path}"
           aws s3 cp "${report_file_path}" "s3://$S3_BUCKET/${report_file_path}"
-          # --quiet
